# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9088182ac609f035c5e6ee60300701bac414352be050edbb69d2a49c7911083c5f09911a40abe49afe407f69f5f12abd09ec08f22a2ec3457d1b52bad5a28c0f

test:
  secret_key_base: 6badc9eda356b439fbed4a5452a40d6993a5723ff6fd96032ab04534d66fa4189998f09208c30074a617bcc5e602c8b0a47ea0866c1ff622ffa11a59e373ade1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
